version: "3.9"
services:
  web:
    build: ./app
    ports:
      - "8887:1234"
    networks:
      - networks  
  frontend:
    build: ./frontend
    ports:
      - "8888:8501" 
    networks:
      - networks 
  postgres:
    container_name: postgres-latest
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres   
    networks:
      - networks   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   
    networks:
      - networks       
networks:
  networks:
    driver: bridge          
   